### ISSUE TITLE
How to grab review

### ISSUE THREAD

**Issue by slucha** [sjaveed/acts_as_nps_rateable#1]
Awesome Gem, really enjoy it for a tool I am building in order to learn rails.
I seem to be able to submit a review as a rater but can not get to display the review by a certain user. How do I get the Review by a rater?
Thank you!

**Comment by sjaveed** [comment]
@slucha I'm glad you're finding it useful :-)  As far as getting a review by a rater, you can do something like the following assuming your User model rated a Restaurant:

``` ruby
me = User.find_by(email: 'slucha@github.com')
mcdonalds = Restaurant.find_by(name: 'McDonalds')

my_rating_of_mcds = me.rating_for(mcdonalds)

the_score_i_gave = my_rating_of_mcds.score
the_review_i_left = my_rating_of_mcds.comments
```

`my_rating_of_mcds` is an `NpsRating` object which contains a score and a review.  It contains additional data as well e.g. count of up_votes/down_votes if you allow voting on ratings etc.

Edit:  You can also get the `NpsRating` object by making a call on the restaurant like so:

``` ruby
my_rating_of_mcds = mcdonalds.rating_by(me)
```

Hope this helps.  Do let me know if this isn't clear!

**Comment by sjaveed** [comment]
@slucha I'm closing this issue.  If you need any more clarification, let me know and I can re-open it.

**Comment by slucha** [comment]
@sjaveed yes, that did the trick. Thank you and sorry for my late reply.
